/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'thalamus\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-action': '&#xe600;',
		'icon-addcalendar': '&#xe601;',
		'icon-airplay': '&#xe602;',
		'icon-alert': '&#xe603;',
		'icon-attach': '&#xe604;',
		'icon-backspace': '&#xe605;',
		'icon-ban': '&#xe606;',
		'icon-barchart': '&#xe607;',
		'icon-battery': '&#xe608;',
		'icon-book': '&#xe609;',
		'icon-bookmark': '&#xe60a;',
		'icon-box': '&#xe60b;',
		'icon-briefcase': '&#xe60c;',
		'icon-buildings': '&#xe60d;',
		'icon-calendar': '&#xe60e;',
		'icon-camera': '&#xe60f;',
		'icon-cart': '&#xe610;',
		'icon-caution': '&#xe611;',
		'icon-cell': '&#xe612;',
		'icon-chat': '&#xe613;',
		'icon-check': '&#xe614;',
		'icon-checkcalendar': '&#xe615;',
		'icon-clock': '&#xe616;',
		'icon-cloud': '&#xe617;',
		'icon-columns': '&#xe618;',
		'icon-compass': '&#xe619;',
		'icon-compose': '&#xe61a;',
		'icon-connection': '&#xe61b;',
		'icon-contract': '&#xe61c;',
		'icon-creditcard': '&#xe61d;',
		'icon-crop': '&#xe61e;',
		'icon-crosshair': '&#xe61f;',
		'icon-cursor': '&#xe620;',
		'icon-dashboard': '&#xe621;',
		'icon-database': '&#xe622;',
		'icon-delete': '&#xe623;',
		'icon-deletecalendar': '&#xe624;',
		'icon-desktop': '&#xe625;',
		'icon-directleft': '&#xe626;',
		'icon-directright': '&#xe627;',
		'icon-directup': '&#xe628;',
		'icon-dislike': '&#xe629;',
		'icon-dollarsign': '&#xe62a;',
		'icon-down': '&#xe62b;',
		'icon-downleft': '&#xe62c;',
		'icon-download': '&#xe62d;',
		'icon-downloadcloud': '&#xe62e;',
		'icon-downloadhdd': '&#xe62f;',
		'icon-downright': '&#xe630;',
		'icon-dropdown': '&#xe631;',
		'icon-droplet': '&#xe632;',
		'icon-eject': '&#xe633;',
		'icon-ellipsis': '&#xe634;',
		'icon-ellipsischat': '&#xe635;',
		'icon-emptybattery': '&#xe636;',
		'icon-erase': '&#xe637;',
		'icon-expand': '&#xe638;',
		'icon-facetime': '&#xe639;',
		'icon-fastforward': '&#xe63a;',
		'icon-fax': '&#xe63b;',
		'icon-femaleuser': '&#xe63c;',
		'icon-file': '&#xe63d;',
		'icon-fill': '&#xe63e;',
		'icon-filter': '&#xe63f;',
		'icon-flag': '&#xe640;',
		'icon-flask': '&#xe641;',
		'icon-folder': '&#xe642;',
		'icon-font': '&#xe643;',
		'icon-fork': '&#xe644;',
		'icon-globe': '&#xe645;',
		'icon-grid': '&#xe646;',
		'icon-halfheart': '&#xe647;',
		'icon-halfstar': '&#xe648;',
		'icon-hdd': '&#xe649;',
		'icon-heart': '&#xe64a;',
		'icon-help': '&#xe64b;',
		'icon-highbattery': '&#xe64c;',
		'icon-highvolume': '&#xe64d;',
		'icon-home': '&#xe64e;',
		'icon-hyphen': '&#xe64f;',
		'icon-inbox': '&#xe650;',
		'icon-info': '&#xe651;',
		'icon-key': '&#xe652;',
		'icon-laptop': '&#xe653;',
		'icon-layers': '&#xe654;',
		'icon-layout': '&#xe655;',
		'icon-left': '&#xe656;',
		'icon-lightbulb': '&#xe657;',
		'icon-like': '&#xe658;',
		'icon-link': '&#xe659;',
		'icon-list': '&#xe65a;',
		'icon-loading': '&#xe65b;',
		'icon-location': '&#xe65c;',
		'icon-lock': '&#xe65d;',
		'icon-logout': '&#xe65e;',
		'icon-lowbattery': '&#xe65f;',
		'icon-lowvolume': '&#xe660;',
		'icon-mail': '&#xe661;',
		'icon-map': '&#xe662;',
		'icon-mediumbattery': '&#xe663;',
		'icon-merge': '&#xe664;',
		'icon-mic': '&#xe665;',
		'icon-move': '&#xe666;',
		'icon-music': '&#xe667;',
		'icon-navigate': '&#xe668;',
		'icon-navigatedown': '&#xe669;',
		'icon-navigateleft': '&#xe66a;',
		'icon-navigateright': '&#xe66b;',
		'icon-navigateup': '&#xe66c;',
		'icon-newspaper': '&#xe66d;',
		'icon-notdef': '&#xe66e;',
		'icon-notebook': '&#xe66f;',
		'icon-notifications': '&#xe670;',
		'icon-notificationsdisabled': '&#xe671;',
		'icon-openbook': '&#xe672;',
		'icon-pause': '&#xe673;',
		'icon-phone': '&#xe674;',
		'icon-phonedisabled': '&#xe675;',
		'icon-picture': '&#xe676;',
		'icon-piechart': '&#xe677;',
		'icon-pin': '&#xe678;',
		'icon-play': '&#xe679;',
		'icon-plus': '&#xe67a;',
		'icon-print': '&#xe67b;',
		'icon-quote': '&#xe67c;',
		'icon-record': '&#xe67d;',
		'icon-redirect': '&#xe67e;',
		'icon-refresh': '&#xe67f;',
		'icon-removecalendar': '&#xe680;',
		'icon-repeat': '&#xe681;',
		'icon-replay': '&#xe682;',
		'icon-reply': '&#xe683;',
		'icon-retweet': '&#xe684;',
		'icon-rewind': '&#xe685;',
		'icon-right': '&#xe686;',
		'icon-rows': '&#xe687;',
		'icon-rss': '&#xe688;',
		'icon-sample': '&#xe689;',
		'icon-search': '&#xe68a;',
		'icon-send': '&#xe68b;',
		'icon-settings': '&#xe68c;',
		'icon-shuffle': '&#xe68d;',
		'icon-signpost': '&#xe68e;',
		'icon-skipback': '&#xe68f;',
		'icon-skipforward': '&#xe690;',
		'icon-star': '&#xe691;',
		'icon-stop': '&#xe692;',
		'icon-stopwatch': '&#xe693;',
		'icon-stroke': '&#xe694;',
		'icon-sync': '&#xe695;',
		'icon-tablet': '&#xe696;',
		'icon-tag': '&#xe697;',
		'icon-target': '&#xe698;',
		'icon-text': '&#xe699;',
		'icon-thumbnails': '&#xe69a;',
		'icon-transfer': '&#xe69b;',
		'icon-trash': '&#xe69c;',
		'icon-unlock': '&#xe69d;',
		'icon-up': '&#xe69e;',
		'icon-upleft': '&#xe69f;',
		'icon-upload': '&#xe6a0;',
		'icon-uploadcloud': '&#xe6a1;',
		'icon-upright': '&#xe6a2;',
		'icon-user': '&#xe6a3;',
		'icon-users': '&#xe6a4;',
		'icon-video': '&#xe6a5;',
		'icon-view': '&#xe6a6;',
		'icon-volume': '&#xe6a7;',
		'icon-warehouse': '&#xe6a8;',
		'icon-wifi': '&#xe6a9;',
		'icon-write': '&#xe6aa;',
		'icon-writingdisabled': '&#xe6ab;',
		'icon-zoomin': '&#xe6ac;',
		'icon-zoomout': '&#xe6ad;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
